version: '1.0'

services:
  app:
    image: wagewise_ml:0.1.0-SNAPSHOT
    container_name: app
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes: # optional to preserve database after container is deleted.
      - ./dev/mongo-data:/data/db
      - ./dev/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
